<?php

/**
* @file
* Provide a simulated beep.
*/
function beep_beep() {
	//echo "beeping!";
	watchdog('beep', 'Beep!');
}

/**
* Implementation of hook_user_login().
function beep_user_login(&$edit, $account) {
//function beep_user(&$edit, $account) {
	beep_beep();
}
*/


/**
* Implementation of hook_node_insert().
function beep_node_insert($node) {
	beep_beep();
}
*/


/**
* Simulate a beep. A Drupal action.
*/
function beep_beep_action() {
	beep_beep();
}

/**
*Implemenation of hook_action_info().
*/
function beep_action_info() {
	return array(
		'beep_beep_action' => array(
			'type' => 'system',
			'label' => t('Beep annoyingly'),
			'configurable' => FALSE,
			'triggers' => array('node_view', 'node_insert', 'node_update', 'node_delete'),
		),
	);
}

