<?php
/**
* @file
* Lets users add private annotations to nodes.
*
* Adds a text field when a node is displayed
* so that authenticated users may make notes.
*/
//
/**
 * Implements hook_menu()
 * @return array
 */

function contenttypepagination_menu() {
  $aItems = array(
      'contenttypepagination' => array(
        'title' => 'content type pagination t',
        'page callback' => '_page_contenttypepagination',
        'access arguments' => array('job_post','start','limit'),
        'page arguments' => array(2,3,4),
        'access callback' => TRUE,
      ),
    );
  return $aItems;
}
 
/**
 * Page callback mapped to the url /hello_world
 *
 * @return array
 */
function _page_contenttypepagination($contenttype="job_post",$start=0,$limit=2) {
    //$result = db_select('node', 'n') ->fields('n') ->execute() ->fetchAssoc();
    $result = db_get_nodes_by_contenttype($contenttype,$start,$limit);
    $page_array['contenttypepagination'] = array(
	//'title' => t('All posts from the last week'),
      	'items' => $result,
      	//Theme hook with suggestion.  
      	'#theme' => 'contenttypepagination',
    );
    return theme('contenttypepagination',$page_array);
    //return theme('pager', $page_array);
}

function db_get_nodes_by_contenttype($contenttype,$start,$limit) {
   // Return all nids of nodes of type "page".
   $nids = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->fields('n', array('type'))
    ->condition('n.type', $contenttype)
    ->range($start,$limit)
    ->execute()
    ->fetchCol(); // returns an indexed array

   // Now return the node objects.
   return node_load_multiple($nids);
}
