<?php
/**
 * Implements hook_menu()
 * @return array
 */

function contenttypepagination_menu() {
  $aItems['contenttypepagination'] = array(
        'title' => t('contenT type pagination'),
        'type' => MENU_LOCAL_TASK,
        'page callback' => '_page_contenttypepagination',
        'access arguments' => array('content access'),
        'access callback' => TRUE,
  );
  return $aItems;
}
 
/**
 * Page callback mapped to the url /hello_world
 *
 * @return array
 */
function _page_contenttypepagination($contenttype='page',$start=0,$limit=20) {
    $r= db_get_nodes_by_contenttype($contenttype,$start,$limit);
    $result=$r[0];
    $count=$r[1];
    $page_array['contenttypepagination'] = array(
	//'title' => t('All posts from the last week'),
      	'items' => $result,
        'count' => $count,
        'start' => $start,
        'limit' => $limit,
        'type' => $contenttype,
    );
    $tpl =  drupal_get_path('module', 'contenttypepagination')."/contenttypepagination.tpl.php";
    return theme_render_template($tpl,$page_array);
}

function db_get_nodes_by_contenttype($contenttype,$start,$limit) {
   // Return all nids of nodes of type "page".
   $nids = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->fields('n', array('type'))
    ->condition('n.type', $contenttype)
    ->range($start,$limit)
    ->execute()
    ->fetchCol(); // returns an indexed array
   $count= db_select('node', 'n')
    ->fields('n', array('nid'))
    ->fields('n', array('type'))
    ->condition('n.type', $contenttype)
    ->countQuery()->execute()->fetchField();

   // Now return the node objects.
   $result=node_load_multiple($nids);
   return array($result,$count);
}
